# Generated by Django 4.2.6 on 2023-10-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.TextField()),
                ('result', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='hw_input',
        ),
        migrations.DeleteModel(
            name='TwoInput',
        ),
        migrations.AddField(
            model_name='allvariables',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
